#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

ideasUnvToFoam trail16.unv						#command to convert .unv mesh to OpenFOAM mesh classes

transformPoints -scale '(0.001 0.001 0.001)'				#converting the domain to SI units of measurement

setFields								#setting the value of certain parameters in a particular region

checkMesh |tee log.CHECKMESH						#checking the mesh quality

createBaffles -dict system/createBaffles1 -overwrite | tee log.flux	#converting facezones in the domain to patches
createBaffles -dict system/createBaffles -overwrite | tee log.water
createBaffles -dict system/createBafflesDict -overwrite | tee log.copper

runApplication decomposePar						#decomposes the domain to run in parallel

mpirun -np 4 icoTempFoam_enthalphy -parallel | tee log.result		#run in parallel using mpi, number of processors, solver name

runApplication reconstructPar						#reconstructs the domain



#------------------------------------------------------------------------------
